repos:
  - repo: local
    hooks:
      - id: sort-json
        name: Ensure jsons files have a unique format.
        entry: python .pre-commit-scripts/ensure_consistent_json.py
        language: python
        files: (extension|keybindings|settings)\.json$
